### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by patrickjamesbarry** [newrelic-experimental/newrelic-java-lettuce#4]
* What went wrong:
A problem occurred configuring root project 'java-instrumentation-template'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve gradle-templates:gradle-templates:1.5.
     Required by:
         project :
      > Could not resolve gradle-templates:gradle-templates:1.5.
         > Could not get resource 'https://dl.bintray.com/cjstehno/public/gradle-templates/gradle-templates/1.5/gradle-templates-1.5.pom'.
            > Could not GET 'https://dl.bintray.com/cjstehno/public/gradle-templates/gradle-templates/1.5/gradle-templates-1.5.pom'. Received status code 403 from server: Forbidden

**Comment by kousalix** [comment]
bintray and jcenter are end of life https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

**Comment by patrickjamesbarry** [comment]
That would do it. Are there any plans to switch to maven or update gradle script to work out-of-the-box?

**Comment by azomshahriar** [comment]
Getting the same issue when building? 
How to proceed?? 

* What went wrong:
A problem occurred configuring root project 'java-instrumentation-template'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve gradle-templates:gradle-templates:1.5.
     Required by:
         project :
      > Could not resolve gradle-templates:gradle-templates:1.5.
         > Could not get resource 'https://dl.bintray.com/cjstehno/public/gradle-templates/gradle-templates/1.5/gradle-templates-1.5.pom'.
            > Could not GET 'https://dl.bintray.com/cjstehno/public/gradle-templates/gradle-templates/1.5/gradle-templates-1.5.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve com.newrelic.agent.java:gradle-verify-instrumentation-plugin:3.2.
     Required by:
         project :
      > Could not resolve com.newrelic.agent.java:gradle-verify-instrumentation-plugin:3.2.
         > Could not get resource 'https://dl.bintray.com/cjstehno/public/com/newrelic/agent/java/gradle-verify-instrumentation-plugin/3.2/gradle-verify-instrumentation-plugin-3.2.pom'.
            > Could not GET 'https://dl.bintray.com/cjstehno/public/com/newrelic/agent/java/gradle-verify-instrumentation-plugin/3.2/gradle-verify-instrumentation-plugin-3.2.pom'. Received status code 502 from server: Bad Gateway

**Comment by dhilpipre** [comment]
Removed dependencies on bintray and replaced with build that works
