### ISSUE TITLE
Getting error when run lettuce agent file

### ISSUE THREAD

**Issue by azomshahriar** [newrelic-experimental/newrelic-java-lettuce#5]

**Comment by dhilpipre** [comment]
Replying to the following:
===================
Getting this when run agent
java -javaagent:Lettuce-6.0.jar -jar target/myapp-0.0.1.jar
Failed to find Premain-Class manifest attribute in Lettuce-6.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument

Any idea?
========

You need to have the New Relic Java Agent installed to use this extension.   You create a directory named extensions in the Java Agent directory (the one containing newrelic.jar).   Copy Lettuce-6.0.jar into the extensions directory.

Run your application as follows:
ava -javaagent:path_to_newrelic.jar -jar target/myapp-0.0.1.jar
